### ISSUE TITLE
QUESTION: How to use $Expand on POST reqeusts

### ISSUE THREAD

**Issue by Gforse12** [unchase/Unchase.Odata.Connectedservice#30]
So OData is still new to me and i figure out by calling $Expand on a GET request i can retrieve objects and collections. However i then whant to change/update them and POST it back but it seems that when calling .SaveChanges it isn't serialized?

**Comment by ChrisSchaller** [comment]
I have this requirement as well, it's not easily supported for actions the same as functions, a work around I used recently was to use BuildingRequest event to inject the additional `$filter` that I wanted to apply, however the same would work for `$expand`:
> the commented code shows the syntax I was expecting to use.

```C#
ClientContext.BuildingRequest += ClientContext_BuildingRequest;
var query = ClientContext.Sensors.ByKey(this.SensorId)
                                 .GetTriggeredSensors(value, this.Timestamp);
       //                        .Where(s => s.VTDisabled == false)
       //                        .Where(s => s.Card.CardType.Driver == cloudVirtualCardDriver);

var items = query.Execute().ToList();
ClientContext.BuildingRequest -= ClientContext_BuildingRequest;

```

```C#
private void ClientContext_BuildingRequest(object sender, Microsoft.OData.Client.BuildingRequestEventArgs e)
{
    if (e.RequestUri.PathAndQuery.Contains("GetTriggeredSensors"))
                e.RequestUri = new System.Uri(e.RequestUri + "?$filter=VTDisabled eq false AND Card/CardType/Driver eq '" + cloudVirtualCardDriver + "'");
}
```

The issue is that `DataServiceActionQuery` (that we use to generate calls to Action endpoints, via POST) only accepts `BodyOperationParameter` as seen in the constructor for [DataServiceActionQuery](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/DataServiceActionQuery.cs) even though internally `ExecuteAsync` accepts `OperationParameter` that could be _Body_ or _Uri_ parameters.

On the flip side of this, `DataServiceQuery` restricts the input to only accept `UriOperationParameter` so we can't even try to work around this issue by using `DataServiceQuery` that targets the _Action_ and then forcing the _Method_ to `"POST"` instead of `"GET"`

I have raised an issue on the ODataLib project regarding a feature that would make supporting this easier: https://github.com/OData/odata.net/issues/1657
