### ISSUE TITLE
BUG in Reference.ttinclude

### ISSUE THREAD

**Issue by THeLenchen** [unchase/Unchase.Odata.Connectedservice#41]
![](https://user-images.githubusercontent.com/25977026/78901658-f1d2a700-7a78-11ea-82d6-b48ccd3a77f9.png)

The File Reference.ttinclude is not empty but returns null or empty string

**Comment by unchase** [comment]
Hi, @THeLenchen 

At the moment, I am focused on improving the [Connected service](https://github.com/OData/ODataConnectedService) by Microsoft and actively contribute to it, since its development has resumed. All features will be transferred to this project. In addition, it is developing faster, so all new features will be added there.

You can create your issues in [this repository](https://github.com/OData/ODataConnectedService/issues).
