### ISSUE TITLE
No option to add authorization header

### ISSUE THREAD

**Issue by naspinski** [unchase/Unchase.Odata.Connectedservice#44]
There is no way to configure this to have a Authorization header to set up your entities

**Comment by unchase** [comment]
Hi, @naspinski 

At the moment, I am focused on improving the [Connected service](https://github.com/OData/ODataConnectedService) by Microsoft and actively contribute to it, since its development has resumed. All features will be transferred to this project. In addition, it is developing faster, so all new features will be added there.

You can create your issues in [this repository](https://github.com/OData/ODataConnectedService/issues).
