### ISSUE TITLE
Add oauth2.0 support

### ISSUE THREAD

**Issue by lianying** [unchase/Unchase.Odata.Connectedservice#57]
Please add oauth2.0 support

**Comment by unchase** [comment]
Hi, @lianying 
Can you describe what do you mean? And how should it look like?

**Comment by axellejamous** [comment]
For me this would be useful too. 
I currently have an oData endpoint I'd like to consume, however the only available authentication option is through client_credentials. Their basic authentication doesn't work as the endpoint hasn't been made public.
I don't know how one would implement this into the extension, though since OAuth2.0 would require you to first make another call to retrieve an authentication header from https://login.microsoftonline.com/ + tenantId.

**Comment by ChrisSchaller** [comment]
As authentication is outside of the OData specification, the guidance around authentication is simply to manage authentication itself outside of the OData request pipeline, and to implement an `OnMessageCreating` function to interact with the transport layer and inject any headers or cookies that may be required.

**Comment by unchase** [comment]
In this case, customization in the connected service is not advisable.
