### ISSUE TITLE
Receiving weird results on different endpoint methods and intermittent Object reference errors

### ISSUE THREAD

**Issue by craigkelly84** [unchase/Unchase.Odata.Connectedservice#72]
Fix your shit.

**Comment by unchase** [comment]
Please be polite when communicating.
Please describe the problem in more detail.

**Comment by ChrisSchaller** [comment]
Many of us are using this library in production environments. 

> In many cases exceptions experienced are actually raised from the API internally or due to the APIs being non-conformant to the OData specification. 
>
> This can be a frustrating experience but there is a lot of collective knowledge available and we genuinely want to help, but we need more information to do that.

To troubleshoot please provide this information:
1. Describe when the issue is experienced, is it at runtime or during the Create or Update connected service experience?
2. Are you using the "Generate T4 file" option?
3. C# or VB
4. Please post the actual exception message in full
5. Please post the related snippet from the $metadata 

Intermittent runtime errors are usually associated with data content or structure. As the client code is generated  from conventions we expect any issues to be consistent around specific data types, relationships or parameters or responses from Actions and Functions. 

Try to identify the pattern behind the failure, if it is a runtime issue then it will help to include a code snippet and evidence that you have tested the same endpoint and query using tools like Postman to isolate the issue to the OData Client generated code.

We're here to help, but without having access to your code project we will need a lot more information.
