### ISSUE TITLE
FEATURE Generate Multiple Files

### ISSUE THREAD

**Issue by luizs81** [unchase/Unchase.Odata.Connectedservice#85]
I tried to find an open feature about this, but couldn't find it.

For huge OData collections, such as the Dynamics 365, would be great to have the option of spliting the Resource file in one file per class, as the OData Client from Microsoft does:

https://docs.microsoft.com/en-us/odata/connectedservice/generating-multiple-files

That would make the management easier and probably consume less memory.

**Comment by unchase** [comment]
Hi, @luizs81
You should use more flexible [Microsoft OData Connected Service](https://github.com/OData/ODataConnectedService) due to the fact that I cant support this project any more (I helped to Microsoft team to implement a big part from this project features into their solution).

P.S. Initially, I started this project and developed it only because the solution from Microsoft was non-functional. However, now it is quite usable. And I do not have enough resources and time to independently bring the project to the level of functionality that Microsoft's solution has. That is why I decided to stop supporting my project, finalizing only the necessary fixes.
